import {Inter} from "next/font/google";
import "./globals.css";
import "./themify-icons.css";
import Header from "./components/Header/page";
import Footer from "./components/Footer/page";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: "Kingsway",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <Header/>
        {children}
        <Footer/>
        </body>
        </html>
    );
}
